### ISSUE TITLE
development environment for Hub 2 generation

### ISSUE THREAD

**Issue by LGO44** [msp1974/aioWiserHeatAPI#1]
@msp1974 thanks in advance for our help
I am using both hub firs generation and second generation.
I want to help our community by updating the API with the new features.
So  I use my development environment like last year, and I try to install the aioWiserHeatAPI

(venv) christian@christian-VirtualBox:~/development$ git clone https://github.com/msp1974/aioWiserHeatAPI.git
Clonage dans 'aioWiserHeatAPI'...
remote: Enumerating objects: 541, done.
remote: Counting objects: 100% (189/189), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 541 (delta 131), reused 119 (delta 69), pack-reused 352
Réception d'objets: 100% (541/541), 129.15 Kio | 3.31 Mio/s, fait.
Résolution des deltas: 100% (364/364), fait.
(venv) christian@christian-VirtualBox:~/development$ cd ~/development/core
(venv) christian@christian-VirtualBox:~/development/core$ source venv/bin/activate
(venv) christian@christian-VirtualBox:~/development/core$ cd ~/development/aioWiserHeatAPI
(venv) christian@christian-VirtualBox:~/development/aioWiserHeatAPI$ pip install -e .
Obtaining file:///home/christian/development/aioWiserHeatAPI
  Preparing metadata (setup.py) ... done
Collecting zeroconf>=0.47.1 (from aioWiserHeatAPI==1.3.4)
  Using cached zeroconf-0.66.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Requirement already satisfied: aiohttp>=3.8.1 in /home/christian/development/core/venv/lib/python3.9/site-packages (from aioWiserHeatAPI==1.3.4) (3.8.1)
Collecting aiofiles>=0.8.0 (from aioWiserHeatAPI==1.3.4)
  Using cached aiofiles-23.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: pyyaml>=6.0 in /home/christian/development/core/venv/lib/python3.9/site-packages (from aioWiserHeatAPI==1.3.4) (6.0)
INFO: pip is looking at multiple versions of aiowiserheatapi to determine which version is compatible with other requirements. This could take a while.
**ERROR: Package 'aiowiserheatapi' requires a different Python: 3.9.17 not in '>=3.10'**
(venv) christian@christian-VirtualBox:~/development/aioWiserHeatAPI$ 

1. I Try to install python3.10 like python3.9, doing that I had to upgrade pip23.1.2 that is not compliant with my previous version of HA  so that it doesn't work anymore.so I try to downgrade to python3.9.

traces 
christian@christian-VirtualBox:~$ cd ~/development/core
christian@christian-VirtualBox:~/development/core$ source venv/bin/activate
(venv) christian@christian-VirtualBox:~/development/core$ hass -c config
Traceback (most recent call last):
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pip 23.1.2 (/home/christian/development/core/venv/lib/python3.9/site-packages), Requirement.parse('pip<22.1,>=21.0'), {'homeassistant'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/christian/development/core/venv/bin/hass", line 33, in <module>
    sys.exit(load_entry_point('homeassistant', 'console_scripts', 'hass')())
  File "/home/christian/development/core/homeassistant/__main__.py", line 159, in main
    args = get_arguments()
  File "/home/christian/development/core/homeassistant/__main__.py", line 69, in get_arguments
    from . import config as config_util
  File "/home/christian/development/core/homeassistant/config.py", line 19, in <module>
    from . import auth
  File "/home/christian/development/core/homeassistant/auth/__init__.py", line 19, in <module>
    from .mfa_modules import MultiFactorAuthModule, auth_mfa_module_from_config
  File "/home/christian/development/core/homeassistant/auth/mfa_modules/__init__.py", line 12, in <module>
    from homeassistant import data_entry_flow, requirements
  File "/home/christian/development/core/homeassistant/requirements.py", line 14, in <module>
    from .util import package as pkg_util
  File "/home/christian/development/core/homeassistant/util/package.py", line 13, in <module>
    import pkg_resources
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/christian/development/core/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip<22.1,>=21.0' distribution was not found and is required by homeassistant

**Comment by LGO44** [comment]
@msp1974 , thank you in advance for any advice and guideline to facilitate future validation work.

**Comment by msp1974** [comment]
OK, you shouldn't need to upgrade pip for the api.  But it does look like you have an out of date HA install.  I would recommend updating this first.

**Firstly, get python 3.10 in your venv.**
1. In development/core delete the venv folder
2. Then recreate your venv with (in your development/core folder)
```
cd /home/christian/development/core
sudo rm -r venv
python3.10 -m venv venv
```
This assumes you have python 3.10 installed on your machine

**Update HA to the latest version**
1. In development/core do 
```
source venv/bin/activate
git pull upstream master
./script/setup
```

Note: when doing a git pull, if it complains that it can't do it because you have uncommited changes, then stash all changes with
```
 git stash
```
And then do the pull again.

**Get the aioWiserHeatAPI and get HA to use it**
1. As you have already cloned the repo, just install into HA while in your HA venv

```
pip install -e /home/christina/developement/aioWiserHeatAPI
```
    Note: this is the same as changing the directory to aioWiserHeatAPI and doing a pip install -e .

**Make sure you have the integration correctly setup**
When I am developing, I like to have the integration in its own folder and then symlink it into HA.  Just find easier to manage.

1. Clone integration repo in same way as aioWiserHeatAPI repo
2.  Symlink it into custom_components
Note:  If you have installed via HACs, then delete the folder /home/christian/development/core/config/custom_components/wiser
```
cd /home/christian/development
git clone https://github.com/asantaga/wiserHomeAssistantPlatform.git
cd core/config/custom_components
ln -s /home/christian/development/wiserHomeAssistantPlatform/custom_components/wiser wiser
```

You should then be able to run HA with
```
hass -c config
```


This should all work as intended but let me know if you get any problems.

**Comment by LGO44** [comment]
Thanks a lot Mark
Now I can work
