### ISSUE TITLE
equipment attribute not well created V1.6.0

### ISSUE THREAD

**Issue by LGO44** [msp1974/aioWiserHeatAPI#22]
@msp1974 
I get some errors for smartplugs and powertags, and heatingacruators, I think that the root cause is in the devices.py build.
my code ran with the previous way to generate the devices but no more now.

some data have been created but not updated ( voltage, current, and power and energy ) 

![image](https://github.com/user-attachments/assets/94b49b5e-8c9d-4f3d-bb83-b47aadf7326a)

logs:

Enregistreur: homeassistant.components.sensor
Source: helpers/entity_platform.py:909
intégration: Sensor ([documentation](https://next.home-assistant.io/integrations/sensor), [problèmes](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
S'est produit pour la première fois: 10:00:54 (1 occurrences)
Dernier enregistrement: 10:00:54

Error adding entity sensor.wiser_powertage_7_voltage for domain sensor with platform wiser
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/home/christian/development/core/config/custom_components/wiser/sensor.py", line 862, in state
    return self._device.equipment.power.rms_voltage
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power'

**Comment by msp1974** [comment]
I'm assuming this is all linked to equipment data info.  Certainly from your log output above, it would seem that the PowerTag with id 7 is not showing any equipment data.

However, I do not see this in my tests with the new build method (yes, the main thing that changed was in devices.py so if there is a problem that is where it will be).  Send me a diag file as I will need to run this and see why there is no equipment data for this device.

**Comment by LGO44** [comment]
here are the 2 diag files of my two houses with equipments...
[config_entry-wiser-04b54a69ee02ea23d613b96cb315965b.json](https://github.com/user-attachments/files/17982482/config_entry-wiser-04b54a69ee02ea23d613b96cb315965b.json)
[config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json](https://github.com/user-attachments/files/17982486/config_entry-wiser-01J42RWFRZPZCJ6R8ATHQBMXMW.json)

**Comment by LGO44** [comment]
Sorry Mark,
I tried the version 1.6.1 but  still have the  issue 

the sensor are initialsed but not refresh....
![image](https://github.com/user-attachments/assets/058fdb09-9df6-4019-8dbc-3747c88c2452)


logs: 
2024-12-03 00:29:53.205 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_plug1_power
2024-12-03 00:29:53.205 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_plug1_total_power
2024-12-03 00:29:53.206 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_frigo_power
2024-12-03 00:29:53.206 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_frigo_total_power
2024-12-03 00:29:53.206 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_ballon_power
2024-12-03 00:29:53.207 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_ballon_total_power
2024-12-03 00:29:53.207 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_chaudiere_power
2024-12-03 00:29:53.207 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_chaudiere_total_power
2024-12-03 00:29:53.208 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_machines_power
2024-12-03 00:29:53.208 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_machines_total_power
2024-12-03 00:29:53.208 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_powertage_7_power_2
2024-12-03 00:29:53.209 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_powertage_7_energy_delivered_2
2024-12-03 00:29:53.209 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.wiser entity: sensor.wiser_powertage_7_energy_received_2
2024-12-03 00:29:53.218 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.wiser_powertage_7_voltage_2 for domain sensor with platform wiser
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/home/christian/development/core/config/custom_components/wiser/sensor.py", line 837, in state
    return self._device.equipment.power.rms_voltage
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power'
2024-12-03 00:29:53.220 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.wiser_powertage_7_current_2 for domain sensor with platform wiser
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/home/christian/development/core/config/custom_components/wiser/sensor.py", line 839, in state
    return self._device.equipment.power.rms_current
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power'
2024-12-03 00:29:53.224 INFO (MainThread) [homeassistant.components.switch] Setting up wiser.switch
2024-12-03 00:29:53.243 INFO (MainThread) [homeassistant.components.select] Setting up wiser.select
2024-12-03 00:29:53.252 INFO (MainThread) [homeassistant.components.button] Setting up wiser.button
2024-12-03 00:29:53.253 INFO (MainThread) [homeassistant.components.number] Setting up wiser.number
2024-12-03 00:29:53.254 INFO (MainThread) [homeassistant.components.light] Setting up wiser.light
2024-12-03 00:29:53.256 INFO (MainThread) [homeassistant.components.cover] Setting up wiser.cover
2024-12-03 00:29:53.582 INFO (MainThread) [custom_components.wiser.coordinator] Hub update completed for WiserHeat045FDD
2024-12-03 00:29:53.605 ERROR (MainThread) [homeassistant.components.binary_sensor] wiser: Error on device update!
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 571, in async_update
    await self.coordinator.async_request_refresh()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/home/christian/development/core/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/home/christian/development/core/config/custom_components/wiser/sensor.py", line 1404, in _handle_coordinator_update
    ).instantaneous_power
      ^^^^^^^^^^^^^^^^^^^
  File "/home/christian/development/aioWiserHeatAPI/aioWiserHeatAPI/pte.py", line 45, in instantaneous_power
    return self.equipment.power.total_active_power
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power'
2024-12-03 00:29:53.614 INFO (MainThread) [custom_components.wiser] Wiser Component Setup Completed (WiserHeat045FDD)
2024-12-03 00:29:53.994 INFO (MainThread) [custom_components.wiser.coordinator] Hub update completed for WiserHeat05E6A6
2024-12-03 00:29:54.007 ERROR (MainThread) [homeassistant.components.binary_sensor] wiser: Error on device update!
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 571, in async_update
    await self.coordinator.async_request_refresh()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/home/christian/development/core/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/home/christian/development/core/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/home/christian/development/core/config/custom_components/wiser/sensor.py", line 1404, in _handle_coordinator_update
    ).instantaneous_power
      ^^^^^^^^^^^^^^^^^^^
  File "/home/christian/development/aioWiserHeatAPI/aioWiserHeatAPI/pte.py", line 45, in instantaneous_power
    return self.equipment.power.total_active_power
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power'
2024-12-03 00:29:54.013 INFO (MainThread) [custom_components.wiser] Wiser Component Setup Completed (WiserHeat05E6A6)

**Comment by msp1974** [comment]
Ok, I think I understand why it is working for me and not for you.  Can you try v1.6.2?  Thx

**Comment by LGO44** [comment]
Everything is fine now.
