### ISSUE TITLE
Json decoder

### ISSUE THREAD

**Issue by LGO44** [msp1974/aioWiserHeatAPI#8]
I have an that come for a few days, it happens 2 or3 times per day.
it seems that the wiser entities are not available that create other errors in the automations the use this kind of variables

aioWiserHeatAPI          1.5.5
Wiser                            3.4.2

Home Assistant

Core                                2024.1.6
Supervisor                     2023.12.1
Operating System         11.4
Frontend                        20240104.0

I have a new error (see logs):

2024-02-01 05:22:56.761 ERROR (MainThread) [custom_components.wiser.coordinator] Expecting value: line 1 column 2791 (char 2790)
2024-02-01 05:22:56.762 ERROR (MainThread) [custom_components.wiser.coordinator] Unexpected error fetching wiser (wiser-WiserHeat03F9E3) data: Expecting value: line 1 column 2791 (char 2790)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiser/coordinator.py", line 151, in async_update_data
    raise ex
  File "/config/custom_components/wiser/coordinator.py", line 129, in async_update_data
    await self.wiserhub.read_hub_data()
  File "/usr/local/lib/python3.11/site-packages/aioWiserHeatAPI/wiserhub.py", line 126, in read_hub_data
    await self._build_objects()
  File "/usr/local/lib/python3.11/site-packages/aioWiserHeatAPI/wiserhub.py", line 146, in _build_objects
    self._schedule_data = await self._wiser_rest_controller._get_hub_data(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioWiserHeatAPI/rest_controller.py", line 187, in _get_hub_data
    return await self._do_hub_action(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioWiserHeatAPI/rest_controller.py", line 126, in _do_hub_action
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2791 (char 2790)

**Comment by msp1974** [comment]
This should be fixed in v1.5.11 onwards
